# Generated by Django 4.0.4 on 2022-05-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarysystem', '0003_alter_issuedbooks_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbooks',
            name='total_charge',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
